### ISSUE TITLE
Markdown in comments / replies

### ISSUE THREAD

**Issue by utmandrew** [utmandrew/virtual-mystery#50]
A suggestion from the T&LS: consider how to provide markdown in the comments and replies, so that students can link images and format their text.

**Comment by hhc97** [comment]
@utmandrew after pr #79 students can now link images and format their text using HTML, is markdown still desired?

**Comment by utmandrew** [comment]
HTML is likely out of a normal person's ability, so markdown would be preferable -- but isn't a high priority.

**Comment by hhc97** [comment]
https://www.npmjs.com/package/ngx-markdown

Saving here for future reference
